### ISSUE TITLE
panic runtime error: index out of range

### ISSUE THREAD

**Issue by beatscode** [arnaud-lb/php-go#6]
I'm getting the following error when trying to reproduce the example on php 7.2.8
```
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "panic: runtime error: index out of range"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: ""
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "goroutine 1 [running]:"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "reflect.(*rtype).In(0x7f9003b3ad60, 0x0, 0x7f9003b3ad60, 0x7f9003b61370)"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: " /usr/local/go/src/reflect/type.go:995 +0x95"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "github.com/arnaud-lb/php-go/php-go.newPHPExport(0x7f90038fe430, 0x10, 0x7f9003b3ad60, 0x7f9003b61370, 0x1, 0xc42000e040, 0x0)"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: " /root/work/src/github.com/arnaud-lb/php-go/php-go/phpgo.go:130 +0x244"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "github.com/arnaud-lb/php-go/php-go.newPHPExports(0xc4200861b0, 0xc420086180, 0x18, 0x0)"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: " /root/work/src/github.com/arnaud-lb/php-go/php-go/phpgo.go:61 +0x11e"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "github.com/arnaud-lb/php-go/php-go.Export(0x7f90038fceec, 0x7, 0xc4200861b0, 0x10)"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: " /root/work/src/github.com/arnaud-lb/php-go/php-go/phpgo.go:47 +0x31"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: "main.init()"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 said into stderr: " /root/work/src/phpgo/test/main.go:10 +0x157"
[30-Jul-2018 12:04:48] WARNING: [pool www] child 23 exited on signal 6 (SIGABRT) after 1739.775042 seconds from start
[30-Jul-2018 12:04:48] NOTICE: [pool www] child 35 started
```

Any sugestions?

**Comment by DasJott** [comment]
same here :/

**Comment by DasJott** [comment]
Pull Request #7 fixes that.
